trigger:
- dev-testing
 
resources:
- repo: self
 
variables:
  tag: 'testing'
 
stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: buildAndPush
        repository: 'backend'
        buildContext: '.'
        containerRegistry: 'docker'
        dockerfile: 'Dockerfile'
        tags: |
          $(tag)

- stage: Test
  displayName: Test
  jobs:
  - job: Test
    displayName: Test
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
        displayName: 'Install Node.js'
    - script: |
        corepack enable pnpm
      displayName: "Enable pnpm"
    - script: |
        pnpm install
      displayName: "Install dependencies"
    - script: |
        pnpm test:ci
      displayName: "Run tests"
    - task: PublishTestResults@2
      displayName: 'Process results'
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: 'junit.xml'

- stage: Deploy
  jobs:
    - deployment: Deploy
      displayName: Deploy
      pool:
        vmImage: 'ubuntu-latest'
      environment: 'development'
      strategy:
        runOnce:
          deploy:
            steps:
            - task: SSH@0
              inputs:
                sshEndpoint: 'development'
                runOptions: 'inline'
                inline: |
                  cd ~/infra/animakuro
                  docker compose pull backend_dev 2>&1
                  docker compose up -d backend_dev 2>&1
                readyTimeout: '20000'